# Generated by Django 5.0.2 on 2024-03-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glass',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
